import { MongoClient } from 'mongodb';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const mongoUrl =
  process.env.DATABASE_URL || 'mongodb://localhost:27017/mutual_funds_db';

const commodityFunds = [
  // ==================== 30 GOLD FUNDS ====================
  {
    amfiCode: 'GOLD001',
    name: 'SBI Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'SBI Mutual Fund',
    nav: 58.42,
    aum: 1250,
    returns: { '1Y': 15.2, '3Y': 16.1, '5Y': 11.5 },
    riskLevel: 'Moderate',
    expenseRatio: 0.52,
    description: 'Gold ETF tracking domestic gold prices, highly liquid',
    inceptionDate: new Date('2011-03-10'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD002',
    name: 'HDFC Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'HDFC Mutual Fund',
    nav: 57.85,
    aum: 980,
    returns: { '1Y': 14.8, '3Y': 15.9, '5Y': 11.2 },
    riskLevel: 'Moderate',
    expenseRatio: 0.48,
    description: 'Low-cost gold ETF with excellent tracking accuracy',
    inceptionDate: new Date('2010-11-15'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD003',
    name: 'ICICI Prudential Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'ICICI Prudential Mutual Fund',
    nav: 59.12,
    aum: 1420,
    returns: { '1Y': 15.5, '3Y': 16.4, '5Y': 11.8 },
    riskLevel: 'Moderate',
    expenseRatio: 0.55,
    description: 'One of the largest gold ETFs in India',
    inceptionDate: new Date('2010-09-20'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD004',
    name: 'Axis Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Axis Mutual Fund',
    nav: 58.75,
    aum: 850,
    returns: { '1Y': 15.1, '3Y': 16.0, '5Y': 11.4 },
    riskLevel: 'Moderate',
    expenseRatio: 0.62,
    description: 'Gold ETF for portfolio diversification and hedging',
    inceptionDate: new Date('2016-04-01'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD005',
    name: 'Kotak Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Kotak Mutual Fund',
    nav: 57.45,
    aum: 720,
    returns: { '1Y': 14.7, '3Y': 15.7, '5Y': 11.0 },
    riskLevel: 'Moderate',
    expenseRatio: 0.95,
    description: 'Gold fund providing commodity exposure',
    inceptionDate: new Date('2011-11-28'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD006',
    name: 'Nippon India Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Nippon India Mutual Fund',
    nav: 58.95,
    aum: 1100,
    returns: { '1Y': 15.4, '3Y': 16.2, '5Y': 11.6 },
    riskLevel: 'Moderate',
    expenseRatio: 0.68,
    description: 'Gold ETF with strong track record since 2009',
    inceptionDate: new Date('2009-07-22'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD007',
    name: 'UTI Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'UTI Mutual Fund',
    nav: 58.2,
    aum: 950,
    returns: { '1Y': 14.9, '3Y': 15.8, '5Y': 11.3 },
    riskLevel: 'Moderate',
    expenseRatio: 0.58,
    description: "Gold ETF from India's oldest mutual fund house",
    inceptionDate: new Date('2010-03-15'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD008',
    name: 'Aditya Birla Sun Life Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Aditya Birla Sun Life Mutual Fund',
    nav: 59.35,
    aum: 890,
    returns: { '1Y': 15.6, '3Y': 16.5, '5Y': 11.9 },
    riskLevel: 'Moderate',
    expenseRatio: 0.72,
    description: 'Gold ETF with consistent performance and liquidity',
    inceptionDate: new Date('2011-05-13'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD009',
    name: 'IDBI Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'IDBI Mutual Fund',
    nav: 57.65,
    aum: 580,
    returns: { '1Y': 14.8, '3Y': 15.9, '5Y': 11.1 },
    riskLevel: 'Moderate',
    expenseRatio: 0.85,
    description: 'Gold ETF tracking MCX gold prices',
    inceptionDate: new Date('2013-08-20'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD010',
    name: 'Edelweiss Gold & Silver ETF FoF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Edelweiss Mutual Fund',
    nav: 24.85,
    aum: 420,
    returns: { '1Y': 13.8, '3Y': 15.2, '5Y': 10.5 },
    riskLevel: 'Moderate',
    expenseRatio: 0.92,
    description: 'Precious metals fund-of-funds combining gold and silver',
    inceptionDate: new Date('2019-01-15'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD011',
    name: 'Bandhan Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Bandhan Mutual Fund',
    nav: 58.05,
    aum: 320,
    returns: { '1Y': 14.9, '3Y': 16.0, '5Y': 11.2 },
    riskLevel: 'Moderate',
    expenseRatio: 0.48,
    description: 'Ultra-low cost gold ETF with perfect tracking',
    inceptionDate: new Date('2020-06-22'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD012',
    name: 'LIC MF Gold Fund',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'LIC Mutual Fund',
    nav: 28.45,
    aum: 280,
    returns: { '1Y': 15.2, '3Y': 16.3, '5Y': 11.5 },
    riskLevel: 'Moderate',
    expenseRatio: 0.95,
    description: 'Gold fund with 99.5% purity tracking',
    inceptionDate: new Date('2013-12-16'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD013',
    name: 'Tata Gold Fund',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Tata Mutual Fund',
    nav: 29.15,
    aum: 350,
    returns: { '1Y': 15.3, '3Y': 16.1, '5Y': 11.3 },
    riskLevel: 'Moderate',
    expenseRatio: 0.78,
    description: 'Gold fund with consistent tracking accuracy',
    inceptionDate: new Date('2011-11-02'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD014',
    name: 'Motilal Oswal Gold & Silver ETF FoF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Motilal Oswal Mutual Fund',
    nav: 18.92,
    aum: 245,
    returns: { '1Y': 14.5, '3Y': 15.8, '5Y': 10.9 },
    riskLevel: 'Moderate',
    expenseRatio: 0.82,
    description: 'Multi-metal commodity fund with gold focus',
    inceptionDate: new Date('2020-09-01'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD015',
    name: 'HSBC Gold Fund',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'HSBC Mutual Fund',
    nav: 32.78,
    aum: 390,
    returns: { '1Y': 15.1, '3Y': 16.2, '5Y': 11.2 },
    riskLevel: 'Moderate',
    expenseRatio: 0.75,
    description: 'Gold fund for diversification and inflation hedge',
    inceptionDate: new Date('2010-10-20'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD016',
    name: 'Franklin India Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Franklin Templeton Mutual Fund',
    nav: 57.92,
    aum: 520,
    returns: { '1Y': 15.0, '3Y': 15.9, '5Y': 11.4 },
    riskLevel: 'Moderate',
    expenseRatio: 0.65,
    description: 'Gold ETF from global asset manager',
    inceptionDate: new Date('2012-04-18'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD017',
    name: 'DSP Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'DSP Mutual Fund',
    nav: 58.48,
    aum: 460,
    returns: { '1Y': 15.2, '3Y': 16.1, '5Y': 11.6 },
    riskLevel: 'Moderate',
    expenseRatio: 0.59,
    description: 'Gold ETF with high liquidity and low tracking error',
    inceptionDate: new Date('2011-08-05'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD018',
    name: 'Invesco India Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Invesco Mutual Fund',
    nav: 59.05,
    aum: 380,
    returns: { '1Y': 15.4, '3Y': 16.3, '5Y': 11.7 },
    riskLevel: 'Moderate',
    expenseRatio: 0.69,
    description: 'Gold ETF backed by physical gold',
    inceptionDate: new Date('2014-03-12'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD019',
    name: 'Quantum Gold Fund',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Quantum Mutual Fund',
    nav: 27.85,
    aum: 215,
    returns: { '1Y': 14.9, '3Y': 16.0, '5Y': 11.3 },
    riskLevel: 'Moderate',
    expenseRatio: 0.78,
    description: 'Gold fund for portfolio stability',
    inceptionDate: new Date('2008-02-01'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD020',
    name: 'Sundaram Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Sundaram Mutual Fund',
    nav: 58.62,
    aum: 295,
    returns: { '1Y': 15.1, '3Y': 16.0, '5Y': 11.4 },
    riskLevel: 'Moderate',
    expenseRatio: 0.71,
    description: 'Gold ETF tracking MCX domestic gold prices',
    inceptionDate: new Date('2015-07-28'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD021',
    name: 'Union Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Union Mutual Fund',
    nav: 57.78,
    aum: 185,
    returns: { '1Y': 14.8, '3Y': 15.8, '5Y': 11.1 },
    riskLevel: 'Moderate',
    expenseRatio: 0.88,
    description: 'Gold ETF for hedging against inflation',
    inceptionDate: new Date('2018-05-10'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD022',
    name: 'BOI AXA Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'BOI AXA Mutual Fund',
    nav: 58.25,
    aum: 165,
    returns: { '1Y': 15.0, '3Y': 15.9, '5Y': 11.2 },
    riskLevel: 'Moderate',
    expenseRatio: 0.82,
    description: 'Gold ETF with 99.5% purity gold backing',
    inceptionDate: new Date('2019-11-20'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD023',
    name: 'Mahindra Manulife Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Mahindra Manulife Mutual Fund',
    nav: 59.18,
    aum: 145,
    returns: { '1Y': 15.5, '3Y': 16.4, '5Y': 11.8 },
    riskLevel: 'Moderate',
    expenseRatio: 0.75,
    description: 'Gold ETF for long-term wealth preservation',
    inceptionDate: new Date('2020-02-14'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD024',
    name: 'Baroda BNP Paribas Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Baroda BNP Paribas Mutual Fund',
    nav: 58.55,
    aum: 125,
    returns: { '1Y': 15.2, '3Y': 16.1, '5Y': 11.5 },
    riskLevel: 'Moderate',
    expenseRatio: 0.79,
    description: 'Gold ETF for portfolio diversification',
    inceptionDate: new Date('2021-03-08'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD025',
    name: 'PGIM India Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'PGIM India Mutual Fund',
    nav: 57.92,
    aum: 105,
    returns: { '1Y': 14.9, '3Y': 16.0, '5Y': 11.3 },
    riskLevel: 'Moderate',
    expenseRatio: 0.68,
    description: 'Gold ETF backed by physical gold reserves',
    inceptionDate: new Date('2021-09-15'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD026',
    name: 'JM Financial Gold Fund',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'JM Financial Mutual Fund',
    nav: 28.72,
    aum: 95,
    returns: { '1Y': 15.1, '3Y': 16.2, '5Y': 11.4 },
    riskLevel: 'Moderate',
    expenseRatio: 0.85,
    description: 'Gold fund for safe-haven allocation',
    inceptionDate: new Date('2016-12-05'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD027',
    name: 'Canara Robeco Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Canara Robeco Mutual Fund',
    nav: 58.38,
    aum: 175,
    returns: { '1Y': 15.0, '3Y': 15.9, '5Y': 11.3 },
    riskLevel: 'Moderate',
    expenseRatio: 0.72,
    description: 'Gold ETF tracking domestic gold prices',
    inceptionDate: new Date('2017-06-22'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD028',
    name: 'Shriram Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Shriram Mutual Fund',
    nav: 59.02,
    aum: 85,
    returns: { '1Y': 15.4, '3Y': 16.3, '5Y': 11.7 },
    riskLevel: 'Moderate',
    expenseRatio: 0.89,
    description: 'Gold ETF for inflation protection',
    inceptionDate: new Date('2022-01-10'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD029',
    name: 'Trust Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Trust Mutual Fund',
    nav: 57.68,
    aum: 75,
    returns: { '1Y': 14.8, '3Y': 15.8, '5Y': 11.1 },
    riskLevel: 'Moderate',
    expenseRatio: 0.78,
    description: 'Gold ETF with low expense ratio',
    inceptionDate: new Date('2022-08-18'),
    isActive: true,
  },
  {
    amfiCode: 'GOLD030',
    name: 'Navi Gold ETF',
    type: 'Commodity',
    category: 'GOLD_ETF',
    subCategory: 'Gold',
    fundHouse: 'Navi Mutual Fund',
    nav: 58.95,
    aum: 65,
    returns: { '1Y': 15.3, '3Y': 16.1, '5Y': 11.5 },
    riskLevel: 'Moderate',
    expenseRatio: 0.45,
    description: 'Ultra-low cost digital-first gold ETF',
    inceptionDate: new Date('2023-02-20'),
    isActive: true,
  },

  // ==================== 30 SILVER FUNDS ====================
  {
    amfiCode: 'SILV001',
    name: 'Axis Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Axis Mutual Fund',
    nav: 72.15,
    aum: 420,
    returns: { '1Y': 8.5, '3Y': 12.3, '5Y': 9.8 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.65,
    description: 'Silver ETF tracking domestic silver prices',
    inceptionDate: new Date('2017-06-22'),
    isActive: true,
  },
  {
    amfiCode: 'SILV002',
    name: 'ICICI Prudential Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'ICICI Prudential Mutual Fund',
    nav: 73.28,
    aum: 380,
    returns: { '1Y': 9.5, '3Y': 13.2, '5Y': 10.5 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.72,
    description: 'Silver ETF with high liquidity',
    inceptionDate: new Date('2018-10-12'),
    isActive: true,
  },
  {
    amfiCode: 'SILV003',
    name: 'SBI Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'SBI Mutual Fund',
    nav: 71.95,
    aum: 350,
    returns: { '1Y': 8.8, '3Y': 12.8, '5Y': 10.2 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.68,
    description: 'Silver investment fund for portfolio diversification',
    inceptionDate: new Date('2019-03-20'),
    isActive: true,
  },
  {
    amfiCode: 'SILV004',
    name: 'Nippon India Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Nippon India Mutual Fund',
    nav: 72.82,
    aum: 295,
    returns: { '1Y': 9.2, '3Y': 11.5, '5Y': 9.5 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.75,
    description: 'Silver ETF with high trading volume',
    inceptionDate: new Date('2018-06-15'),
    isActive: true,
  },
  {
    amfiCode: 'SILV005',
    name: 'Aditya Birla Sun Life Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Aditya Birla Sun Life Mutual Fund',
    nav: 73.45,
    aum: 265,
    returns: { '1Y': 9.8, '3Y': 13.5, '5Y': 10.8 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.82,
    description: 'Silver fund for industrial metal exposure',
    inceptionDate: new Date('2017-09-28'),
    isActive: true,
  },
  {
    amfiCode: 'SILV006',
    name: 'HDFC Silver ETF FoF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'HDFC Mutual Fund',
    nav: 18.92,
    aum: 240,
    returns: { '1Y': 8.2, '3Y': 12.0, '5Y': 9.4 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.78,
    description: 'Silver fund-of-funds for easy investing',
    inceptionDate: new Date('2020-01-15'),
    isActive: true,
  },
  {
    amfiCode: 'SILV007',
    name: 'UTI Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'UTI Mutual Fund',
    nav: 72.38,
    aum: 220,
    returns: { '1Y': 8.9, '3Y': 12.6, '5Y': 10.0 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.69,
    description: 'Silver ETF tracking MCX silver prices',
    inceptionDate: new Date('2019-08-05'),
    isActive: true,
  },
  {
    amfiCode: 'SILV008',
    name: 'Kotak Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Kotak Mutual Fund',
    nav: 71.85,
    aum: 195,
    returns: { '1Y': 8.4, '3Y': 12.1, '5Y': 9.6 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.89,
    description: 'Silver fund for precious metals allocation',
    inceptionDate: new Date('2020-11-10'),
    isActive: true,
  },
  {
    amfiCode: 'SILV009',
    name: 'DSP Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'DSP Mutual Fund',
    nav: 72.95,
    aum: 175,
    returns: { '1Y': 9.3, '3Y': 13.0, '5Y': 10.3 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.72,
    description: 'Silver ETF with low tracking error',
    inceptionDate: new Date('2021-02-18'),
    isActive: true,
  },
  {
    amfiCode: 'SILV010',
    name: 'Franklin Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Franklin Templeton Mutual Fund',
    nav: 28.45,
    aum: 155,
    returns: { '1Y': 8.6, '3Y': 12.4, '5Y': 9.8 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.85,
    description: 'Silver fund for industrial precious metal exposure',
    inceptionDate: new Date('2021-07-22'),
    isActive: true,
  },
  {
    amfiCode: 'SILV011',
    name: 'Invesco Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Invesco Mutual Fund',
    nav: 73.12,
    aum: 135,
    returns: { '1Y': 9.4, '3Y': 13.1, '5Y': 10.4 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.76,
    description: 'Silver ETF backed by physical silver',
    inceptionDate: new Date('2022-01-10'),
    isActive: true,
  },
  {
    amfiCode: 'SILV012',
    name: 'Edelweiss Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Edelweiss Mutual Fund',
    nav: 72.28,
    aum: 115,
    returns: { '1Y': 8.7, '3Y': 12.5, '5Y': 9.9 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.88,
    description: 'Silver ETF for commodity diversification',
    inceptionDate: new Date('2022-06-15'),
    isActive: true,
  },
  {
    amfiCode: 'SILV013',
    name: 'Bandhan Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Bandhan Mutual Fund',
    nav: 71.75,
    aum: 95,
    returns: { '1Y': 8.3, '3Y': 11.9, '5Y': 9.5 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.65,
    description: 'Low-cost silver ETF for retail investors',
    inceptionDate: new Date('2023-03-20'),
    isActive: true,
  },
  {
    amfiCode: 'SILV014',
    name: 'IDBI Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'IDBI Mutual Fund',
    nav: 29.18,
    aum: 85,
    returns: { '1Y': 8.8, '3Y': 12.7, '5Y': 10.1 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.92,
    description: 'Silver fund tracking domestic prices',
    inceptionDate: new Date('2021-09-05'),
    isActive: true,
  },
  {
    amfiCode: 'SILV015',
    name: 'LIC MF Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'LIC Mutual Fund',
    nav: 72.58,
    aum: 75,
    returns: { '1Y': 9.0, '3Y': 12.8, '5Y': 10.2 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.79,
    description: 'Silver ETF for hedging inflation',
    inceptionDate: new Date('2022-11-18'),
    isActive: true,
  },
  {
    amfiCode: 'SILV016',
    name: 'Tata Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Tata Mutual Fund',
    nav: 28.92,
    aum: 65,
    returns: { '1Y': 8.5, '3Y': 12.2, '5Y': 9.7 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.82,
    description: 'Silver fund for industrial metal allocation',
    inceptionDate: new Date('2023-05-10'),
    isActive: true,
  },
  {
    amfiCode: 'SILV017',
    name: 'Quantum Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Quantum Mutual Fund',
    nav: 73.05,
    aum: 55,
    returns: { '1Y': 9.2, '3Y': 13.0, '5Y': 10.3 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.75,
    description: 'Silver ETF with 99.9% purity backing',
    inceptionDate: new Date('2023-08-22'),
    isActive: true,
  },
  {
    amfiCode: 'SILV018',
    name: 'Mahindra Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Mahindra Manulife Mutual Fund',
    nav: 72.42,
    aum: 45,
    returns: { '1Y': 8.9, '3Y': 12.6, '5Y': 10.0 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.86,
    description: 'Silver fund for precious metal diversification',
    inceptionDate: new Date('2024-01-15'),
    isActive: true,
  },
  {
    amfiCode: 'SILV019',
    name: 'HSBC Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'HSBC Mutual Fund',
    nav: 71.88,
    aum: 38,
    returns: { '1Y': 8.4, '3Y': 12.0, '5Y': 9.6 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.78,
    description: 'Silver ETF from global banking leader',
    inceptionDate: new Date('2024-04-10'),
    isActive: true,
  },
  {
    amfiCode: 'SILV020',
    name: 'Sundaram Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Sundaram Mutual Fund',
    nav: 29.35,
    aum: 32,
    returns: { '1Y': 8.7, '3Y': 12.5, '5Y': 9.9 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.89,
    description: 'Silver fund for industrial exposure',
    inceptionDate: new Date('2024-07-20'),
    isActive: true,
  },
  {
    amfiCode: 'SILV021',
    name: 'BOI AXA Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'BOI AXA Mutual Fund',
    nav: 72.78,
    aum: 28,
    returns: { '1Y': 9.1, '3Y': 12.9, '5Y': 10.2 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.81,
    description: 'Silver ETF for alternative investment',
    inceptionDate: new Date('2024-09-15'),
    isActive: true,
  },
  {
    amfiCode: 'SILV022',
    name: 'Union Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Union Mutual Fund',
    nav: 28.62,
    aum: 24,
    returns: { '1Y': 8.5, '3Y': 12.3, '5Y': 9.7 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.92,
    description: 'Silver fund tracking MCX prices',
    inceptionDate: new Date('2024-11-05'),
    isActive: true,
  },
  {
    amfiCode: 'SILV023',
    name: 'Canara Robeco Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Canara Robeco Mutual Fund',
    nav: 73.18,
    aum: 21,
    returns: { '1Y': 9.4, '3Y': 13.2, '5Y': 10.5 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.74,
    description: 'Silver ETF for precious metal portfolio',
    inceptionDate: new Date('2025-01-10'),
    isActive: true,
  },
  {
    amfiCode: 'SILV024',
    name: 'PGIM Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'PGIM India Mutual Fund',
    nav: 72.05,
    aum: 18,
    returns: { '1Y': 8.6, '3Y': 12.4, '5Y': 9.8 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.87,
    description: 'Silver fund for commodity allocation',
    inceptionDate: new Date('2025-03-15'),
    isActive: true,
  },
  {
    amfiCode: 'SILV025',
    name: 'Motilal Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Motilal Oswal Mutual Fund',
    nav: 71.95,
    aum: 15,
    returns: { '1Y': 8.3, '3Y': 11.9, '5Y': 9.5 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.79,
    description: 'Silver ETF for industrial metal exposure',
    inceptionDate: new Date('2025-05-20'),
    isActive: true,
  },
  {
    amfiCode: 'SILV026',
    name: 'JM Financial Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'JM Financial Mutual Fund',
    nav: 29.08,
    aum: 12,
    returns: { '1Y': 8.8, '3Y': 12.7, '5Y': 10.0 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.95,
    description: 'Silver fund for precious metal hedge',
    inceptionDate: new Date('2025-07-08'),
    isActive: true,
  },
  {
    amfiCode: 'SILV027',
    name: 'Baroda Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Baroda BNP Paribas Mutual Fund',
    nav: 72.52,
    aum: 10,
    returns: { '1Y': 9.0, '3Y': 12.8, '5Y': 10.1 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.82,
    description: 'Silver ETF for portfolio diversification',
    inceptionDate: new Date('2025-09-12'),
    isActive: true,
  },
  {
    amfiCode: 'SILV028',
    name: 'Shriram Silver Fund',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Shriram Mutual Fund',
    nav: 28.75,
    aum: 8,
    returns: { '1Y': 8.4, '3Y': 12.1, '5Y': 9.6 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.91,
    description: 'Silver fund for alternative assets',
    inceptionDate: new Date('2025-10-18'),
    isActive: true,
  },
  {
    amfiCode: 'SILV029',
    name: 'Trust Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Trust Mutual Fund',
    nav: 73.25,
    aum: 6,
    returns: { '1Y': 9.5, '3Y': 13.3, '5Y': 10.6 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.76,
    description: 'Silver ETF for industrial precious metal',
    inceptionDate: new Date('2025-11-05'),
    isActive: true,
  },
  {
    amfiCode: 'SILV030',
    name: 'Navi Silver ETF',
    type: 'Commodity',
    category: 'SILVER_ETF',
    subCategory: 'Silver',
    fundHouse: 'Navi Mutual Fund',
    nav: 72.85,
    aum: 5,
    returns: { '1Y': 9.2, '3Y': 13.0, '5Y': 10.3 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.55,
    description: 'Ultra-low cost digital silver ETF',
    inceptionDate: new Date('2025-11-15'),
    isActive: true,
  },

  // ==================== 20 OTHER METAL FUNDS (Copper, Platinum, etc.) ====================
  {
    amfiCode: 'METAL001',
    name: 'ICICI Prudential Commodities Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'ICICI Prudential Mutual Fund',
    nav: 18.65,
    aum: 350,
    returns: { '1Y': 7.2, '3Y': 10.5, '5Y': 8.9 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.95,
    description: 'Multi-commodity fund with gold, silver, copper exposure',
    inceptionDate: new Date('2019-05-10'),
    isActive: true,
  },
  {
    amfiCode: 'METAL002',
    name: 'Axis Commodity Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'Axis Mutual Fund',
    nav: 22.45,
    aum: 285,
    returns: { '1Y': 6.8, '3Y': 10.5, '5Y': 8.5 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.25,
    description: 'Diversified commodity exposure including industrial metals',
    inceptionDate: new Date('2021-02-10'),
    isActive: true,
  },
  {
    amfiCode: 'METAL003',
    name: 'HDFC Commodity Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'HDFC Mutual Fund',
    nav: 20.18,
    aum: 245,
    returns: { '1Y': 7.5, '3Y': 11.2, '5Y': 9.2 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.18,
    description: 'Commodity fund including copper, zinc, aluminum',
    inceptionDate: new Date('2020-08-15'),
    isActive: true,
  },
  {
    amfiCode: 'METAL004',
    name: 'SBI Multi-Commodity Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'SBI Mutual Fund',
    nav: 19.85,
    aum: 220,
    returns: { '1Y': 7.0, '3Y': 10.8, '5Y': 8.8 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.15,
    description: 'Broad commodity basket for portfolio diversification',
    inceptionDate: new Date('2021-06-20'),
    isActive: true,
  },
  {
    amfiCode: 'METAL005',
    name: 'Nippon India Commodity Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'Nippon India Mutual Fund',
    nav: 21.32,
    aum: 195,
    returns: { '1Y': 7.8, '3Y': 11.5, '5Y': 9.5 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.28,
    description: 'Multi-commodity fund with metals and energy exposure',
    inceptionDate: new Date('2020-11-05'),
    isActive: true,
  },
  {
    amfiCode: 'METAL006',
    name: 'Kotak Commodity Allocation Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'Kotak Mutual Fund',
    nav: 18.92,
    aum: 175,
    returns: { '1Y': 6.5, '3Y': 10.2, '5Y': 8.4 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.32,
    description:
      'Tactical commodity allocation across precious and base metals',
    inceptionDate: new Date('2022-01-18'),
    isActive: true,
  },
  {
    amfiCode: 'METAL007',
    name: 'Aditya Birla Commodity Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'Aditya Birla Sun Life Mutual Fund',
    nav: 22.85,
    aum: 155,
    returns: { '1Y': 8.2, '3Y': 11.8, '5Y': 9.8 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.22,
    description: 'Diversified commodity fund with global exposure',
    inceptionDate: new Date('2021-09-10'),
    isActive: true,
  },
  {
    amfiCode: 'METAL008',
    name: 'DSP Industrial Metals Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Industrial Metals',
    fundHouse: 'DSP Mutual Fund',
    nav: 24.15,
    aum: 135,
    returns: { '1Y': 5.8, '3Y': 9.5, '5Y': 7.8 },
    riskLevel: 'High',
    expenseRatio: 1.45,
    description: 'Focus on copper, aluminum, zinc for industrial growth',
    inceptionDate: new Date('2022-05-22'),
    isActive: true,
  },
  {
    amfiCode: 'METAL009',
    name: 'UTI Commodity Allocation Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'UTI Mutual Fund',
    nav: 19.48,
    aum: 115,
    returns: { '1Y': 6.9, '3Y': 10.6, '5Y': 8.6 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.18,
    description: 'Balanced commodity portfolio including energy',
    inceptionDate: new Date('2023-02-15'),
    isActive: true,
  },
  {
    amfiCode: 'METAL010',
    name: 'Franklin Commodity Opportunities',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'Franklin Templeton Mutual Fund',
    nav: 23.72,
    aum: 95,
    returns: { '1Y': 8.5, '3Y': 12.2, '5Y': 10.2 },
    riskLevel: 'High',
    expenseRatio: 1.38,
    description: 'Actively managed commodity fund with global metals',
    inceptionDate: new Date('2022-10-08'),
    isActive: true,
  },
  {
    amfiCode: 'METAL011',
    name: 'Invesco Base Metals Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Industrial Metals',
    fundHouse: 'Invesco Mutual Fund',
    nav: 21.95,
    aum: 85,
    returns: { '1Y': 6.2, '3Y': 9.8, '5Y': 8.1 },
    riskLevel: 'High',
    expenseRatio: 1.52,
    description: 'Copper, nickel, lead exposure for construction boom',
    inceptionDate: new Date('2023-06-12'),
    isActive: true,
  },
  {
    amfiCode: 'METAL012',
    name: 'Edelweiss Commodity FoF',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'Edelweiss Mutual Fund',
    nav: 17.82,
    aum: 75,
    returns: { '1Y': 7.1, '3Y': 10.9, '5Y': 8.9 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.28,
    description: 'Fund-of-funds with broad commodity coverage',
    inceptionDate: new Date('2024-01-20'),
    isActive: true,
  },
  {
    amfiCode: 'METAL013',
    name: 'Mahindra Metals & Mining Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Mining',
    fundHouse: 'Mahindra Manulife Mutual Fund',
    nav: 26.45,
    aum: 65,
    returns: { '1Y': 5.5, '3Y': 9.2, '5Y': 7.5 },
    riskLevel: 'High',
    expenseRatio: 1.65,
    description: 'Mining companies and base metal exposure',
    inceptionDate: new Date('2024-05-15'),
    isActive: true,
  },
  {
    amfiCode: 'METAL014',
    name: 'HSBC Platinum Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Precious Metals',
    fundHouse: 'HSBC Mutual Fund',
    nav: 32.18,
    aum: 55,
    returns: { '1Y': 4.8, '3Y': 8.5, '5Y': 7.1 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.42,
    description: 'Platinum and palladium exposure for auto industry',
    inceptionDate: new Date('2023-09-05'),
    isActive: true,
  },
  {
    amfiCode: 'METAL015',
    name: 'Tata Multi-Commodity Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'Tata Mutual Fund',
    nav: 20.55,
    aum: 48,
    returns: { '1Y': 7.3, '3Y': 11.0, '5Y': 9.0 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.25,
    description: 'Diversified commodity exposure including steel',
    inceptionDate: new Date('2024-08-10'),
    isActive: true,
  },
  {
    amfiCode: 'METAL016',
    name: 'Bandhan Copper Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Industrial Metals',
    fundHouse: 'Bandhan Mutual Fund',
    nav: 28.92,
    aum: 42,
    returns: { '1Y': 6.5, '3Y': 10.2, '5Y': 8.3 },
    riskLevel: 'High',
    expenseRatio: 1.58,
    description: 'Pure copper exposure for electrical and construction sectors',
    inceptionDate: new Date('2025-02-18'),
    isActive: true,
  },
  {
    amfiCode: 'METAL017',
    name: 'LIC MF Commodity Diversified',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'LIC Mutual Fund',
    nav: 19.28,
    aum: 38,
    returns: { '1Y': 6.8, '3Y': 10.4, '5Y': 8.5 },
    riskLevel: 'Moderate to High',
    expenseRatio: 1.35,
    description: 'Multi-metal commodity fund for inflation hedge',
    inceptionDate: new Date('2025-05-12'),
    isActive: true,
  },
  {
    amfiCode: 'METAL018',
    name: 'Quantum Aluminum Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Industrial Metals',
    fundHouse: 'Quantum Mutual Fund',
    nav: 25.75,
    aum: 32,
    returns: { '1Y': 5.2, '3Y': 8.8, '5Y': 7.2 },
    riskLevel: 'High',
    expenseRatio: 1.48,
    description: 'Aluminum exposure for aerospace and automobile industries',
    inceptionDate: new Date('2025-07-20'),
    isActive: true,
  },
  {
    amfiCode: 'METAL019',
    name: 'PGIM Zinc & Lead Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Industrial Metals',
    fundHouse: 'PGIM India Mutual Fund',
    nav: 22.38,
    aum: 28,
    returns: { '1Y': 6.0, '3Y': 9.5, '5Y': 7.8 },
    riskLevel: 'High',
    expenseRatio: 1.55,
    description: 'Zinc and lead exposure for galvanizing and battery sectors',
    inceptionDate: new Date('2025-09-15'),
    isActive: true,
  },
  {
    amfiCode: 'METAL020',
    name: 'Navi Commodity Basket Fund',
    type: 'Commodity',
    category: 'COMMODITY',
    subCategory: 'Multi-Commodity',
    fundHouse: 'Navi Mutual Fund',
    nav: 18.45,
    aum: 25,
    returns: { '1Y': 7.5, '3Y': 11.3, '5Y': 9.3 },
    riskLevel: 'Moderate to High',
    expenseRatio: 0.85,
    description: 'Low-cost digital commodity fund with broad metal exposure',
    inceptionDate: new Date('2025-11-01'),
    isActive: true,
  },
];

async function main() {
  console.log('🚀 Starting Commodity Funds Seeding...');
  console.log(`📊 Total funds to add: ${commodityFunds.length}`);
  console.log(
    `   - Gold Funds: 30\n   - Silver Funds: 30\n   - Other Metal Funds: 20\n`
  );

  const client = new MongoClient(mongoUrl);

  try {
    await client.connect();
    console.log('✓ Connected to MongoDB');

    const db = client.db();
    const fundsCollection = db.collection('funds');

    let addedCount = 0;
    let skippedCount = 0;

    for (const fund of commodityFunds) {
      const existing = await fundsCollection.findOne({
        amfiCode: fund.amfiCode,
      });

      if (!existing) {
        await fundsCollection.insertOne({
          ...fund,
          createdAt: new Date(),
          updatedAt: new Date(),
        });
        addedCount++;
        console.log(`✓ Added: ${fund.name} (${fund.category})`);
      } else {
        skippedCount++;
        console.log(`⊘ Skipped (exists): ${fund.name}`);
      }
    }

    console.log('\n🎉 Commodity Funds Seeding Complete!');
    console.log(`   ✅ Added: ${addedCount} funds`);
    console.log(`   ⊘ Skipped: ${skippedCount} funds (already exist)`);
    console.log(`   📊 Total in database: ${addedCount + skippedCount}`);
  } catch (error) {
    console.error('❌ Error seeding commodity funds:', error);
    throw error;
  } finally {
    await client.close();
    console.log('\n✓ Database connection closed');
  }
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
